---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 01f131b43f4a263915231b0c40fe149645867f9b
    app.quarkus.io/build-timestamp: 2023-02-23 - 14:06:43 +0000
  labels:
    app.kubernetes.io/name: orm
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: orm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orm
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 01f131b43f4a263915231b0c40fe149645867f9b
        app.quarkus.io/build-timestamp: 2023-02-23 - 14:06:43 +0000
      labels:
        app.kubernetes.io/name: orm
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: andreas.hansen/orm:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: orm
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 01f131b43f4a263915231b0c40fe149645867f9b
    app.quarkus.io/build-timestamp: 2023-02-23 - 14:06:43 +0000
  labels:
    app.kubernetes.io/name: orm
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: orm
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: orm
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
