quarkus:
  http:
    port: 8080
  rabbitmq:
    devservices:
      enabled: true
      port: 5672
      http-port: 15672
      shared: true
      service-name: shared-rmq

#rabbitmq-host : localhost
#rabbitmq-port : 5672

mp:
  messaging:
    incoming:
      ticket-orders:
        connector: smallrye-rabbitmq
        queue:
          name: ticket-orders
        exchange:
          name: ticket-orders
          durable: true
          type: topic
      ticket-activations:
        connector: smallrye-rabbitmq
        queue:
          name: ticket-activations
        exchange:
          name: ticket-activations
          durable: true
          type: topic
"#dev":
  rabbitmq-host: localhost
  rabbitmq-port: 5672
