quarkus:
  http:
    port: 8080
  rabbitmq:
    devservices:
      enabled: true
      port: 5672
      http-port: 15672
      shared: true
      service-name: shared-rmq

#rabbitmq-host : localhost
#rabbitmq-port : 5672

mp:
  messaging:
    incoming:
      ticket-order-request:
        connector: smallrye-rabbitmq
        queue:
          name: ticket-order-request
        exchange:
          name: ticket-order-request
          durable: true
          type: topic
      ticket-activate-request:
        connector: smallrye-rabbitmq
        queue:
          name: ticket-activate-request
        exchange:
          name: ticket-activate-request
          durable: true
          type: topic
      ticket-create-request:
        connector: smallrye-rabbitmq
        queue:
          name: ticket-create-request
        exchange:
          name: ticket-create-request
          durable: true
          type: topic
"#dev":
  rabbitmq-host: localhost
  rabbitmq-port: 5672
