quarkus:
  http:
    port: 8082
    test-port: 18082
    test-timeout : 10s
  rabbitmq:
    devservices :
      enabled: true
      port : 5672
      http-port : 15672
      shared : true
      service-name : shared-rmq
mp:
  messaging:
    outgoing:
      tickets-create-request:
        connector: smallrye-rabbitmq
        exchange:
          name: ticket-create-request
          type: topic
      ticket-activate-request:
        connector: smallrye-rabbitmq
        exchange:
          name: ticket-activate-request
          type: topic
      ticket-order-request:
        connector: smallrye-rabbitmq
        exchange:
          name: ticket-order-request
          type: topic

#rabbitmq-host : localhost
#rabbitmq-port : 5672
